---
- name: "(passwords) add user {{ user }} to user/password dict"
  ansible.builtin.set_fact:
    takel_users_passwords: >-
      {{ takel_users_passwords |
      default({}) |
      combine( {user: password_hash} ) }}
